import { Project } from "@/types/imo";

// Mock 数据 - 用于开发和测试
export const mockProjects: Project[] = [
  {
    id: "1",
    ticker: "$CURSOR",
    name: "Cursor",
    logo: "https://cursor.sh/brand/icon.svg",
    description: "AI-first code editor that helps you build software faster.",
    website: "https://cursor.sh",
    twitter: "https://twitter.com/cursor_ai",
    github: "https://github.com/getcursor",
    status: "launched",
    chain: "solana",
    launchpad: "pump.fun",
    scout_id: "scout1",
    scout_wallet: "7xKXtg...",
    discovered_at: "2026-01-25T10:00:00Z",
    current_bid_amount: 2.5,
    bid_count: 5,
    token_address: "CURx...abc",
    launched_at: "2026-01-25T12:00:00Z",
    verify_twitter: true,
    verify_github: true,
    verify_website: false,
    verify_official: false,
    created_at: "2026-01-25T10:00:00Z",
    updated_at: "2026-01-26T08:00:00Z",
  },
  {
    id: "2",
    ticker: "$BOLT",
    name: "Bolt.new",
    logo: "https://bolt.new/favicon.svg",
    description: "Prompt, run, edit, and deploy full-stack web apps.",
    website: "https://bolt.new",
    twitter: "https://twitter.com/stackaborflow",
    status: "claimed",
    chain: "solana",
    launchpad: "pump.fun",
    scout_id: "scout2",
    scout_wallet: "9zLYuh...",
    discovered_at: "2026-01-24T08:00:00Z",
    current_bid_amount: 5.2,
    bid_count: 12,
    token_address: "BLTx...abc",
    launched_at: "2026-01-24T12:00:00Z",
    claimed_at: "2026-01-25T12:00:00Z",
    verify_twitter: true,
    verify_github: false,
    verify_website: true,
    verify_official: true,
    created_at: "2026-01-24T08:00:00Z",
    updated_at: "2026-01-25T12:00:00Z",
  },
  {
    id: "3",
    ticker: "$LOVABLE",
    name: "Lovable",
    logo: "https://lovable.dev/favicon.ico",
    description: "The last piece of software you'll ever build. AI-powered full-stack development.",
    website: "https://lovable.dev",
    twitter: "https://twitter.com/lovaborflow",
    status: "launching",
    chain: "solana",
    launchpad: "pump.fun",
    scout_id: "scout3",
    scout_wallet: "5bMZui...",
    discovered_at: "2026-01-26T06:00:00Z",
    current_bid_amount: 1.0,
    bid_count: 3,
    verify_twitter: false,
    verify_github: false,
    verify_website: false,
    verify_official: false,
    created_at: "2026-01-26T06:00:00Z",
    updated_at: "2026-01-26T06:00:00Z",
  },
  {
    id: "4",
    ticker: "$DEVIN",
    name: "Devin",
    logo: "https://devin.ai/favicon.ico",
    description: "The world's first AI software engineer.",
    website: "https://devin.ai",
    twitter: "https://twitter.com/cognition_labs",
    github: "https://github.com/cognition-labs",
    status: "launched",
    chain: "bsc",
    launchpad: "flap.sh",
    scout_id: "scout1",
    scout_wallet: "7xKXtg...",
    discovered_at: "2026-01-26T02:00:00Z",
    current_bid_amount: 0.15,
    bid_count: 8,
    token_address: "0xDEV...abc",
    launched_at: "2026-01-26T04:00:00Z",
    verify_twitter: true,
    verify_github: true,
    verify_website: true,
    verify_official: false,
    created_at: "2026-01-26T02:00:00Z",
    updated_at: "2026-01-26T08:00:00Z",
  },
  {
    id: "5",
    ticker: "$V0",
    name: "v0.dev",
    logo: "https://v0.dev/icon-dark.svg",
    description: "Chat with v0. Generate UI with simple text prompts.",
    website: "https://v0.dev",
    twitter: "https://twitter.com/v0",
    status: "claimed",
    chain: "solana",
    launchpad: "trends.fun",
    scout_id: "scout4",
    scout_wallet: "4cNZvi...",
    discovered_at: "2026-01-23T10:00:00Z",
    current_bid_amount: 8.8,
    bid_count: 20,
    token_address: "V0xx...xyz",
    launched_at: "2026-01-23T14:00:00Z",
    creator_id: "vercel",
    creator_wallet: "7ePZxi...",
    claimed_at: "2026-01-25T10:00:00Z",
    verify_twitter: true,
    verify_github: true,
    verify_website: true,
    verify_official: true,
    created_at: "2026-01-23T10:00:00Z",
    updated_at: "2026-01-25T10:00:00Z",
  },
  {
    id: "6",
    ticker: "$REPLIT",
    name: "Replit Agent",
    description: "Build apps with AI. From idea to deployed in seconds.",
    website: "https://replit.com",
    twitter: "https://twitter.com/Replit",
    github: "https://github.com/replit",
    status: "discovering",
    chain: "solana",
    scout_id: "scout5",
    scout_wallet: "8fQYyj...",
    discovered_at: "2026-01-26T07:00:00Z",
    current_bid_amount: 0,
    bid_count: 0,
    verify_twitter: false,
    verify_github: false,
    verify_website: false,
    verify_official: false,
    created_at: "2026-01-26T07:00:00Z",
    updated_at: "2026-01-26T07:00:00Z",
  },
];

// 获取项目列表
export function getProjects(filter?: {
  status?: string;
  chain?: string;
}): Project[] {
  let filtered = [...mockProjects];
  
  if (filter?.status && filter.status !== 'all') {
    filtered = filtered.filter(p => p.status === filter.status);
  }
  
  if (filter?.chain && filter.chain !== 'all') {
    filtered = filtered.filter(p => p.chain === filter.chain);
  }
  
  return filtered;
}

// 根据 Ticker 获取项目
export function getProjectByTicker(ticker: string): Project | undefined {
  const normalizedTicker = ticker.startsWith('$') ? ticker : `$${ticker.toUpperCase()}`;
  return mockProjects.find(p => p.ticker.toUpperCase() === normalizedTicker.toUpperCase());
}
